config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do

    authenticated :user do

      root 'posts#index', as: :authenticated_root

    end

    unauthenticated do

      root 'users/sessions#new', as: :unauthenticated_root

    end

  end

  devise_for :users, controllers: {

      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'

  }

  resources :friend_requests
  resources :friend_ships
  resources :posts do
    resources :comments
    resources  :likes
  end

end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  def self.incoming_requests(current_user)

       FriendRequest.where(friend: current_user).map{|incoming_request| incoming_request.user}

  end

  def self.send_requests(current_user)

       current_user.friend_requests.map{|friend_request| friend_request.friend}

  end

  def accept

    user.friends << friend
    friend.friend_ships.create(friend: user)
    destroy

  end

end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, only: [:show, :edit, :destroy]

  def index

    @incoming_requests = FriendRequest.incoming_requests(current_user)
    @send_requests = FriendRequest.send_requests(current_user)
    @users = ((User.where.not(id: current_user) - @send_requests) - @incoming_requests) - current_user.friends

  end

  def create

    friend = User.find(params[:friend_id])
    @friend_request = current_user.friend_requests.build(friend: friend)

    if @friend_request.save
      redirect_to friend_requests_path, notice: 'Friend request was successfully Sent.'
    else
      redirect_to authenticated_root
    end

  end

  def update

    @friend_request = FriendRequest.where(user_id: params[:id], friend_id: current_user).first
    @friend_request.accept

    respond_to do |format|
      format.html { redirect_to friend_requests_url, notice: 'Friend request was successfully Accepted.' }
    end

  end

  def destroy

    @friend_request.destroy
    respond_to do |format|
      format.html { redirect_to friend_requests_url, notice: 'Friend request was successfully deleted.' }
    end

  end

  private

  def set_friend_request

    @friend_request = FriendRequest.where(user_id: current_user, friend_id: params[:id]).first

  end

end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/views/friend_requests/_accept_request.html.erb
<h3>Accept Requests</h3>
<% @incoming_requests.each do |incoming_request| %>
  <div class="row">
    <%= incoming_request.first_name %>
    <%= link_to 'Accept Friend Request', friend_request_path(id: incoming_request), method: :put%>
  </div>
<% end %>

app/views/friend_requests/_form.html.erb
<%= form_with(model: friend_request, local: true) do |form| %>
  <% if friend_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend_request.errors.count, "error") %> prohibited this friend_request from being saved:</h2>

      <ul>
        <% friend_request.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :friend_id %>
    <%= form.number_field :friend_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friend_requests/_send_request.html.erb
<h3>Send Requests</h3>
<% @send_requests.each do |send_request| %>
  <div class="row">
    <%= send_request.first_name %>
    <%= link_to 'Cancel Friend Request', friend_request_path(id: send_request), method: :delete%>
  </div>
<% end %>

app/views/friend_requests/edit.html.erb
<h1>Editing Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Show', @friend_request %> |
<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>


  <%= render "friend_requests/accept_request", collection: @incoming_requests, locals: {size: 30} %>

  <%= render "friend_requests/send_request", collection: @send_requests, locals: {size: 30} %>

  <h3>Users Lists</h3>

  <% @users.each do |user| %>
    <div class="row">
      <%= user.first_name %>
      <%= link_to "Add friend", friend_requests_path(@users, :friend_id => user.id), :method=> :post %>
    </div>
  <% end %>
</div>

app/views/friend_requests/new.html.erb
<h1>New Friend Request</h1>

<%= render 'form', friend_request: @friend_request %>

<%= link_to 'Back', friend_requests_path %>

app/views/friend_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friend_request.user_id %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friend_request.friend_id %>
</p>

<%= link_to 'Edit', edit_friend_request_path(@friend_request) %> |
<%= link_to 'Back', friend_requests_path %>