config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do

    authenticated :user do

      root 'posts#index', as: :authenticated_root

    end

    unauthenticated do

      root 'users/sessions#new', as: :unauthenticated_root

    end

  end

  devise_for :users, controllers: {

      registrations: 'users/registrations',
      sessions: 'users/sessions',
      passwords: 'users/passwords'

  }

  resources :friend_requests
  resources :friend_ships
  resources :posts do
    resources :comments
    resources  :likes
  end

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :comments
  has_many :likes, as: :likeable

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index

    @posts = Post.all

  end

  def new

    @post = Post.new

  end

  def create

      @post = current_user.posts.build(post_params)
      if @post.save
        redirect_to authenticated_root_path, notice: 'Post was successfully Created.'
      else
        redirect_to authenticated_root_path, notice: 'Post not created'
      end

  end

  def show
  end

  def update
  end

  def destroy
  end

  private

  def post_params

    params.require(:post).permit(:content, :avatar)

  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def current_user_post_like(post, current_user)

      post.likes.where(user_id: current_user)

  end

  def current_user_comment_like(comment, current_user)

    comment.likes.where(user_id: current_user)

  end

end

app/views/posts/_post_form.html.erb
<%= form_for @post do |form| %>

  <div class="field">
    <%= form.text_area :content %>
  </div>

  <div class="field">
      <%= form.file_field :avatar %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="row">
    <%= link_to 'Post', new_post_path %>
  </div>
 <% @posts.each do |post| %>
    <div class="row">
      <%= post.content %>
    </div>
    <div class="row">
      <%= image_tag post.avatar.url, style: 'height:200px;width:400px;'%>
    </div>
    <%  if can? :update, post %>
      <%= link_to 'Comment  ', new_post_comment_path(post), post: post %>
      <% if current_user_post_like(post, current_user).count > 0 %>
        <%= link_to 'UnLike ', post_like_path(post_id: post.id, id: current_user_post_like(post, current_user).first), method: :delete %>
      <% else %>
          <%= link_to 'Like ', post_likes_path(post_id: post.id), method: :post %>
      <% end %>
    <%end%>
    <% if post.likes.count > 0 %>
           <%= post.likes.count %>
    <% end %>
      <%post.comments.each do |comment| %>
       <div class="row">
         <%= link_to comment.user_first_name %>
         <%= comment.content %>
         <% if current_user_comment_like(comment, current_user).count > 0 %>
           <%= link_to 'UnLike ', post_like_path(post_id: post.id, comment_id: comment.id, id: current_user_comment_like(comment, current_user).first), method: :delete %>
         <% else %>
           <%= link_to 'Like ',post_likes_path(post_id: post.id, comment_id: comment.id), method: :post %>
         <% end %>
         <%if comment.likes.count > 0 %>
               <%= comment.likes.count %>
         <% end %>
       </div>
      <% end %>

  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>
  <%= render 'post_form', post: @post %>
</div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>